name: ExplosionRegeneration
main: me.foncused.explosionregeneration.ExplosionRegeneration
version: '${version}'
author: foncused, Envel
api-version: 1.19

commands:
  blockregenspeed:
    usage: /<command>
    aliases: []
    description: Change block regeneration speed

permissions:
  explosionregeneration.blockregenspeed:
    default: false
