name: ExplosionRegeneration
main: me.foncused.explosionregeneration.ExplosionRegeneration
version: 1.4.7
author: foncused, Envel
api-version: 1.18

commands:
  blockregenspeed:
    usage: /<command>
    aliases: []
    description: Change block regeneration speed

permissions:
  explosionregeneration.blockregenspeed:
    default: false
